# Generated by Django 5.1.1 on 2024-09-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='flower_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.flower'),
            preserve_default=False,
        ),
    ]
