# Generated by Django 5.1.1 on 2024-09-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
