# Generated by Django 5.1.1 on 2024-09-05 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('flower_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_orders.order'),
        ),
    ]
