# Generated by Django 5.1.1 on 2024-09-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_orders', '0002_remove_orderitem_flower_name'),
        ('shop', '0005_remove_orderitem_order_remove_orderitem_flower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flower'),
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
