# Generated by Django 5.1.1 on 2024-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_orders', '0003_alter_orderitem_flower_delete_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
