# Generated by Django 5.1.1 on 2024-09-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_orders', '0004_order_order_details_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
